sudo: required

services:
  - docker

env:
  SHORT_COMMIT=`echo $TRAVIS_COMMIT | cut -c1-7`
  CURRENT_DATE=`date '+%Y%m%d%H%M%S'`
  TAG="${CURRENT_DATE}_${SHORT_COMMIT}"
  PATH=/snap/bin:$PATH

before_install:
  - tar -czvf resources/ resources.tar.gz
  - docker build -t dnanexus/parliament2:$TAG .

script:
  echo "hello world"
  # Placeholder for running an entire test suite
  # - docker run -v $PWD:/workdir -w /workdir -e DX_API_TOKEN=$DX_API_TOKEN dnanexus/dxda:$TAG download -max_threads=`nproc` test_files/single_file.manifest.json.bz2
  # # If all the tests pass, push the docker image and create a release
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

branches:
  except:
  - hgsc

language: python
python: 
  - "3.4"